version: '3'

services:
  restaurantes-rest:
    build: 
      context: .
      dockerfile: restaurantes-rest/Dockerfile
    restart: always
    ports:
      - 8080:8080
    links:
      - "opiniones-rest:opiniones-rest"
    environment:
      - URI_MONGODB=mongodb://arso:arso@ac-muzzzdk-shard-00-00.yhy3vkv.mongodb.net:27017,ac-muzzzdk-shard-00-01.yhy3vkv.mongodb.net:27017,ac-muzzzdk-shard-00-02.yhy3vkv.mongodb.net:27017/?ssl=true&replicaSet=atlas-gvuc5f-shard-0&authSource=admin&retryWrites=true&w=majority
      - RABBITMQ_URI=amqps://dbuadusv:RUItokUvjf65IFZDxkDZ6J1Z3punicMq@rat.rmq2.cloudamqp.com/dbuadusv
      - RABBITMQ_EXCHANGE=amq.direct
      - RABBITMQ_QUEUE=arso
      - RABBITMQ_ROUTING_KEY=arso      
          
  opiniones-rest:
    build: 
      context: opiniones-rest
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5041:5041
    environment:
      - URI_MONGODB=mongodb+srv://arso:arso@cluster0.yhy3vkv.mongodb.net/?retryWrites=true&w=majority
      - RABBITMQ_URI=amqps://dbuadusv:RUItokUvjf65IFZDxkDZ6J1Z3punicMq@rat.rmq2.cloudamqp.com/dbuadusv
      - RABBITMQ_EXCHANGE=amq.direct
      - RABBITMQ_QUEUE=arso
      - RABBITMQ_ROUTING_KEY=arso

  pasarela:
    build:
      context: .
      dockerfile: pasarela/Dockerfile
    restart: always
    ports:
      - 8090:8090
    links:
      - "restaurantes-rest:restaurantes-rest"
      - "opiniones-rest:opiniones-rest"
    environment:    
      - URI_REDIRECCION=http://localhost:3000 # redirección web de DaWEB
